# Generated by Django 4.2.7 on 2023-12-03 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0003_alter_category_options_alter_news_options_news_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land', models.CharField(max_length=255, verbose_name='Страна')),
                ('age', models.IntegerField(max_length=10, verbose_name='Возраст')),
                ('photo', models.ImageField(blank=True, default=None, null=True, upload_to='profiles/%Y/%m/%d/', verbose_name='Фото')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.AddField(
            model_name='news',
            name='profiles',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='news.profiles', verbose_name='Категория'),
        ),
    ]
